[system]
compatible=raspberrypi4-64
bootloader=custom
statusfile=/var/lib/rauc/system.conf

[handlers]
bootloader-custom-backend=/usr/lib/rauc/boot-select.sh

[keyring]
path=/etc/rauc/ca.cert.pem
use-bundle-signing-time=true

[slot.boot.0]
device=/dev/mmcblk0p1
type=vfat
extra-mount-opts=uid=0,gid=0

[slot.rootfs.0]
device=/dev/mmcblk0p2
type=ext4
bootname=A

[slot.rootfs.1]
device=/dev/mmcblk0p3
type=ext4
bootname=B
